

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Collections.ObjectModel;
using WPFLocales.DesignTime;

namespace SampleApplication.Localization.DesignTimeData
{
	/// <summary>
    /// Design time locale: EN
    /// </summary>
	public class ENDesignTimeLocale : DesignTimeLocale
	{
		public ENDesignTimeLocale() : base("EN", "EN")
		{
							Values = new Dictionary<string, IDictionary<string,string>>
				{
									{
						"SampleApplication", 
						new Dictionary<string, string>(new Dictionary<string, string>
						{
												{ "StateLabelContent", "Состояние:" },
												{ "StateLabelContentFormat", "Состояние: {0}" },
												{ "StateErrorText", "Ошибка" },
												{ "StateOkText", "Норма" },
												{ "ChangeStateButtonContent", "Именить состояние" },
												{ "LocaleLabelContent", "Локаль:" },
												})
					},
									{
						"SampleApplication2", 
						new Dictionary<string, string>(new Dictionary<string, string>
						{
												{ "StateLabelContent", "Состояние:" },
												{ "StateLabelContentFormat", "Состояние: {0}" },
												{ "StateErrorText", "Ошибка" },
												{ "StateOkText", "Норма" },
												{ "ChangeStateButtonContent", "Именить состояние" },
												{ "LocaleLabelContent", "Локаль:" },
												})
					},
								};
					}
	}
}