// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SampleApplication.Localization
{
	/// <summary>
    /// Keys for localization
    /// </summary>
	public static class LocalizationKeys
	{
									/// <summary>
				/// TEST
				/// </summary>
				public enum SampleApplication
				{
											/// <summary>
						/// Состояние бла бла бла
						/// </summary>
						StateLabelContent,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						StateLabelContentFormat,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						StateErrorText,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						StateOkText,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						ChangeStateButtonContent,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						LocaleLabelContent,
								
				}
							/// <summary>
				///  No comment for this group in default locale 
				/// </summary>
				public enum SampleApplication2
				{
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						StateLabelContent,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						StateLabelContentFormat,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						StateErrorText,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						StateOkText,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						ChangeStateButtonContent,
											/// <summary>
						///  No comment for this item in default locale 
						/// </summary>
						LocaleLabelContent,
								
				}
						}
}